//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer : Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.member = false;
            this.stays = 0;
        }
    
        public string expirationDate { get; set; }
        public bool member { get; set; }
        public string password { get; set; }
        public Nullable<int> loyaltyNum { get; set; }
        public int stays { get; set; }
        public Nullable<System.DateTime> lastStay { get; set; }
    
        public virtual RoomType RoomPref { get; set; }
    }
}
