//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Collections.Generic;
    using System.Web.Helpers;

    public partial class Customer : Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer(string firstname, string lastname, string email, string sessionId, DateTime sessionExp,
            string password, string phone, string address, string state,
            string city, string zip)
       {
            this.firstName = firstname;
            this.lastName = lastname;
            this.email = email;
            this.sessionId = sessionId;
            this.phone = phone;
            this.address = address;
            this.state = state;
            this.city = city;
            this.zip = zip;
            this.sessionExpiration = sessionExp;

            this.member = false;
            this.password = Crypto.HashPassword(password);
            this.loyaltyNum = 0;
            this.stays = 0;
            this.lastStay = null;
            this.RoomPref = null;
        }

        public Customer()
        {
            this.member = false;
            this.stays = 0;
        }

        public Nullable<System.DateTime> expirationDate { get; set; }
        public bool member { get; set; }
        public string password { get; set; }
        public Nullable<int> loyaltyNum { get; set; }
        public int stays { get; set; }
        public Nullable<System.DateTime> lastStay { get; set; }
    
        public virtual RoomType RoomPref { get; set; }
    }
}
