//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservation
    {
        [Required(ErrorMessage = "Check-in date is required")]
        public System.DateTime checkIn { get; set; }
        [Required(ErrorMessage = "Check-out date is required")]
        public System.DateTime checkOut { get; set; }
        public int Id { get; set; }
        public double bill { get; set; }
        [Required(ErrorMessage = "Guest info is required")]
        public string guestsInfo { get; set; }
        public virtual Room Room { get; set; }
        [Required(ErrorMessage = "People is required")]
        public virtual Person People { get; set; }
    }
}
