//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class RoomType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomType()
        {
            this.basePrice = 0D;
            this.maxGuests = 2;
            this.Rooms = new HashSet<Room>();
        }
    
        public int Id { get; set; }
        public string type { get; set; }
        public double basePrice { get; set; }
        public int maxGuests { get; set; }
        public int numberOfRooms { get; set; }
        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
    public class RoomTypeContext : DbContext
    {
        public RoomTypeContext() : base("DefaultConnection") { }
        public DbSet<RoomType> RoomTypes { get; set; }

    }
}
